import Link from 'next/link';
import { Header } from '@/components/Header';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { CheckCircle, BarChart, Goal, Bot } from 'lucide-react';

export default function Home() {
  const features = [
    {
      icon: <BarChart className="h-10 w-10 text-primary" />,
      title: 'Comprehensive Financial Assessment',
      description: 'Get a clear picture of your financial health with our detailed assessment tool.',
    },
    {
      icon: <Bot className="h-10 w-10 text-primary" />,
      title: 'AI-Powered Reports',
      description: 'Receive personalized reports and actionable insights generated by our advanced AI.',
    },
    {
      icon: <Goal className="h-10 w-10 text-primary" />,
      title: 'Personalized Goal Tracking',
      description: 'Set and track your financial goals with our intuitive and easy-to-use interface.',
    },
    {
      icon: <CheckCircle className="h-10 w-10 text-primary" />,
      title: 'Actionable Recommendations',
      description: 'Our AI provides clear, step-by-step recommendations to help you achieve your financial goals.',
    },
  ];

  return (
    <div className="flex min-h-screen flex-col bg-background font-sans text-foreground">
      <Header />
      <main className="flex-1">
        <section className="container mx-auto flex flex-col items-center justify-center space-y-8 px-4 py-20 text-center">
          <h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl md:text-6xl">
            Your Personal AI Financial Guide
          </h1>
          <p className="max-w-2xl text-lg text-muted-foreground sm:text-xl">
            Acash.ai provides you with the insights and tools you need to take control of your
            finances and build a secure future.
          </p>
          <Button asChild size="lg" className="text-lg">
            <Link href="/assessment">Start Assessment</Link>
          </Button>
        </section>

        <section id="features" className="w-full bg-muted py-20">
          <div className="container mx-auto">
            <div className="mx-auto mb-12 max-w-3xl text-center">
              <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
                Features to Help You Succeed
              </h2>
              <p className="mt-4 text-lg text-muted-foreground">
                Everything you need to understand and improve your financial health.
              </p>
            </div>
            <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-4">
              {features.map((feature) => (
                <Card key={feature.title} className="flex flex-col items-center text-center">
                  <CardHeader>
                    {feature.icon}
                  </CardHeader>
                  <CardContent>
                    <CardTitle className="mb-2 text-xl">{feature.title}</CardTitle>
                    <p className="text-muted-foreground">{feature.description}</p>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
